<%@ Page Language="C#" AutoEventWireup="true" trace="true" CodeBehind="CarParkingSiteDetails.aspx.cs" Inherits="CarParkingBooking.GridViewForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gvCarParkingSiteDetails" runat="server" AutoGenerateColumns="false" ShowFooter="true" DataKeyNames="serialNo" ShowHeaderWhenEmpty="true"  AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="gvCarParkingSiteDetails_RowCancelingEdit" OnRowDeleting="gvCarParkingSiteDetails_RowDeleting" OnRowEditing="gvCarParkingSiteDetails_RowEditing" OnRowUpdating="gvCarParkingSiteDetails_RowUpdating" CellSpacing="4">
                <Columns>
                    <asp:TemplateField HeaderText="serialNo">
                <EditItemTemplate>
                    <asp:TextBox ID="textserialNo" runat="server" Text='<%# Container.DataItemIndex +1%>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelserialNo" runat="server" Text='<%# Bind("serialNo") %>'></asp:Label>
                </ItemTemplate>
                 <FooterTemplate>
                    <asp:LinkButton ID="linkInsert" runat="server" Text="Insert" OnClick="linkInsert_Click"></asp:LinkButton>
                </FooterTemplate>
               <%-- <FooterTemplate>
                    <asp:TextBox ID="txtPackageId" runat="server"></asp:TextBox>
                </FooterTemplate>--%>
            </asp:TemplateField>
                    <asp:TemplateField HeaderText="CarParkingSiteName">
                        <ItemTemplate>
                            <asp:Label Text='<%#Eval("siteName") %>' runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtsitetName" Text='<%#Eval("siteName") %>' runat="server" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtsiteNameFooter" runat="server" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="location">
                        <ItemTemplate>
                            <asp:Label Text='<%#Eval("location") %>' runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtlocation" Text='<%#Eval("location") %>' runat="server" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtlocationFooter" runat="server" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="MailId">
                        <ItemTemplate>
                            <asp:Label Text='<%#Eval("emailId") %>' runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtemailId" Text='<%#Eval("emailId") %>' runat="server" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtemailIdFooter" runat="server" />
                        </FooterTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Available Parking Slots">
                        <ItemTemplate>
                            <asp:Label Text='<%#Eval("parkingSlots") %>' runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtparkingSlots" Text='<%#Eval("parkingSlots") %>' runat="server" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtparkingSlotsFooter" runat="server" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:ImageButton ImageUrl="~/Images/Update.jfif" runat="server" CommandName="Edit" ToolTip="Edit" Width="20px" Height="20px" />
                            <asp:ImageButton ImageUrl="~/Images/Delete.jfif" runat="server" CommandName="Delete" ToolTip="Delete" Width="20px" Height="20px" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:ImageButton ImageUrl="~/Images/Save.png" runat="server" CommandName="Update" ToolTip="Update" Width="20px" Height="20px" />
                            <asp:ImageButton ImageUrl="~/Images/Cancel.jfif" runat="server" CommandName="Cancel" ToolTip="Cancel" Width="20px" Height="20px" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:ImageButton ImageUrl="~/Images/Add.png" runat="server" CommandName="Add New" ToolTip="Add New" Width="20px" Height="20px" />
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <asp:Label ID="lblSuccessMessage" Text="" runat="server" ForeColor="Green" />
            <br />
           <asp:Label ID="lblErrorMessage" Text="" runat="server" ForeColor="Red" />
        </div>
    </form>
</body>
</html>
